# Generated by Django 3.2.12 on 2022-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worker_type',
            field=models.CharField(choices=[('all', 'Hammasi'), ('freelancer', 'Freelancer'), ('team', 'Team'), ('company', 'Company')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
