# Generated by Django 3.2 on 2022-02-07 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('legal_entity', 'Legal entity')], max_length=30, null=True, verbose_name='Client type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=125, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_related_info',
            field=models.IntegerField(null=True, verbose_name='Related info'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='fullname',
            field=models.CharField(max_length=125, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='passport_given_date',
            field=models.DateField(verbose_name='Passport given date'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='passport_issued_address',
            field=models.CharField(max_length=255, verbose_name='Passport issued address'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='passport_number',
            field=models.CharField(max_length=20, verbose_name='Passport number'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='passport_series',
            field=models.CharField(max_length=10, verbose_name='Passport series'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_account',
            field=models.CharField(max_length=255, verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_name',
            field=models.CharField(max_length=255, verbose_name='Bank name'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='fullname',
            field=models.CharField(max_length=125, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='ifut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IFUT'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='inn',
            field=models.CharField(max_length=255, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='mfo',
            field=models.CharField(max_length=255, verbose_name='MFO'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='telegram_phone',
            field=models.CharField(max_length=20, verbose_name='Telegram phone'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Otp code'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires in'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone number'),
        ),
    ]
