# Generated by Django 3.2 on 2022-02-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220208_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='client',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='client',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Otp code'),
        ),
    ]
